version: '3'
services:
    redis:
        image: redis:alpine
        ports:
            - 30001:6379
        networks:
            - crypto-network
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis_data:/data
        command: redis-server /usr/local/etc/redis/redis.conf

    postgres:
        image: postgres:latest
        ports:
            - 30002:5432
        networks:
            - crypto-network
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres

    stream_data:
        build:
            context: stream_data
        depends_on:
            - redis
            - postgres
        cpus: 0.1
        networks:
            - crypto-network
        restart: always
        mem_limit: 200m
        memswap_limit: 200m
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./logs:/app/logs

networks:
    crypto-network:
        driver: bridge
