"""empty message

Revision ID: 037a7241bc74
Revises: 
Create Date: 2023-10-12 10:46:05.159926

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '037a7241bc74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=10), nullable=False),
    sa.Column('quote_asset', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptos_base_asset'), 'cryptos', ['base_asset'], unique=False)
    op.create_index(op.f('ix_cryptos_id'), 'cryptos', ['id'], unique=False)
    op.create_index(op.f('ix_cryptos_quote_asset'), 'cryptos', ['quote_asset'], unique=False)
    op.create_index(op.f('ix_cryptos_symbol'), 'cryptos', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_cryptos_symbol'), table_name='cryptos')
    op.drop_index(op.f('ix_cryptos_quote_asset'), table_name='cryptos')
    op.drop_index(op.f('ix_cryptos_id'), table_name='cryptos')
    op.drop_index(op.f('ix_cryptos_base_asset'), table_name='cryptos')
    op.drop_table('cryptos')
    # ### end Alembic commands ###
