"""empty message

Revision ID: 46b0a2a2b332
Revises: 85a7e33acc90
Create Date: 2023-10-14 12:32:09.663906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b0a2a2b332'
down_revision: Union[str, None] = '85a7e33acc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_alert_association',
    sa.Column('crypto_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_alert_association')
    # ### end Alembic commands ###
