"""empty message

Revision ID: 85a7e33acc90
Revises: 4f65b5bada46
Create Date: 2023-10-14 12:26:08.724643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a7e33acc90'
down_revision: Union[str, None] = '4f65b5bada46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cryptos_id', table_name='cryptos')
    op.drop_index('ix_cryptos_symbol', table_name='cryptos')
    op.create_unique_constraint(None, 'cryptos', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cryptos', type_='unique')
    op.create_index('ix_cryptos_symbol', 'cryptos', ['symbol'], unique=False)
    op.create_index('ix_cryptos_id', 'cryptos', ['id'], unique=False)
    # ### end Alembic commands ###
