"""empty message

Revision ID: 8df0f3377645
Revises: 037a7241bc74
Create Date: 2023-10-13 15:46:57.009994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df0f3377645'
down_revision: Union[str, None] = '037a7241bc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cryptos_base_asset', table_name='cryptos')
    op.drop_index('ix_cryptos_quote_asset', table_name='cryptos')
    op.drop_index('ix_cryptos_symbol', table_name='cryptos')
    op.create_index(op.f('ix_cryptos_symbol'), 'cryptos', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptos_symbol'), table_name='cryptos')
    op.create_index('ix_cryptos_symbol', 'cryptos', ['symbol'], unique=False)
    op.create_index('ix_cryptos_quote_asset', 'cryptos', ['quote_asset'], unique=False)
    op.create_index('ix_cryptos_base_asset', 'cryptos', ['base_asset'], unique=False)
    # ### end Alembic commands ###
