"""empty message

Revision ID: 4f65b5bada46
Revises: f26ebcef1c8e
Create Date: 2023-10-14 12:22:10.745833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f65b5bada46'
down_revision: Union[str, None] = 'f26ebcef1c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('klines', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('params',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('alerts', 'interval')
    op.drop_column('alerts', 'params')
    op.drop_column('alerts', 'is_active')
    op.drop_column('alerts', 'klines')
    op.drop_column('alerts', 'value')
    op.drop_column('alerts', 'condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('klines', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('params')
    op.drop_table('indicators')
    # ### end Alembic commands ###
